psiblast -query ./fasta/1A34.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1A34.pssm
psiblast -query ./fasta/1A9N.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1A9N.pssm
psiblast -query ./fasta/1ASY.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1ASY.pssm
psiblast -query ./fasta/1AV6.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1AV6.pssm
psiblast -query ./fasta/1B23.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1B23.pssm
psiblast -query ./fasta/1B7F.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1B7F.pssm
psiblast -query ./fasta/1BMV.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1BMV.pssm
psiblast -query ./fasta/1C0A.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1C0A.pssm
psiblast -query ./fasta/1CVJ.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1CVJ.pssm
psiblast -query ./fasta/1DDL.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1DDL.pssm
psiblast -query ./fasta/1DFU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1DFU.pssm
psiblast -query ./fasta/1DI2.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1DI2.pssm
psiblast -query ./fasta/1E7K.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1E7K.pssm
psiblast -query ./fasta/1E8O.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1E8O.pssm
psiblast -query ./fasta/1EC6.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1EC6.pssm
psiblast -query ./fasta/1EIY.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1EIY.pssm
psiblast -query ./fasta/1F7U.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1F7U.pssm
psiblast -query ./fasta/1F8V.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1F8V.pssm
psiblast -query ./fasta/1FEU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1FEU.pssm
psiblast -query ./fasta/1FFY.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1FFY.pssm
psiblast -query ./fasta/1G1X.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1G1X.pssm
psiblast -query ./fasta/1GAX.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1GAX.pssm
psiblast -query ./fasta/1GTF.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1GTF.pssm
psiblast -query ./fasta/1H38.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1H38.pssm
psiblast -query ./fasta/1H3E.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1H3E.pssm
psiblast -query ./fasta/1HC8.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1HC8.pssm
psiblast -query ./fasta/1HYS.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1HYS.pssm
psiblast -query ./fasta/1I6U.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1I6U.pssm
psiblast -query ./fasta/1J1U.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1J1U.pssm
psiblast -query ./fasta/1J2B.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1J2B.pssm
psiblast -query ./fasta/1JBR.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1JBR.pssm
psiblast -query ./fasta/1JID.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1JID.pssm
psiblast -query ./fasta/1K8W.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1K8W.pssm
psiblast -query ./fasta/1KNZ.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1KNZ.pssm
psiblast -query ./fasta/1KOG.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1KOG.pssm
psiblast -query ./fasta/1KQ2.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1KQ2.pssm
psiblast -query ./fasta/1L9A.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1L9A.pssm
psiblast -query ./fasta/1M8V.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1M8V.pssm
psiblast -query ./fasta/1M8X.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1M8X.pssm
psiblast -query ./fasta/1MJI.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1MJI.pssm
psiblast -query ./fasta/1MMS.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1MMS.pssm
psiblast -query ./fasta/1MZP.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1MZP.pssm
psiblast -query ./fasta/1N78.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1N78.pssm
psiblast -query ./fasta/1OOA.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1OOA.pssm
psiblast -query ./fasta/1P6V.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1P6V.pssm
psiblast -query ./fasta/1Q2R.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1Q2R.pssm
psiblast -query ./fasta/1QF6.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1QF6.pssm
psiblast -query ./fasta/1QTQ.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1QTQ.pssm
psiblast -query ./fasta/1R3E.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1R3E.pssm
psiblast -query ./fasta/1RC7.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1RC7.pssm
psiblast -query ./fasta/1RPU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1RPU.pssm
psiblast -query ./fasta/1S03.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1S03.pssm
psiblast -query ./fasta/1SDS.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1SDS.pssm
psiblast -query ./fasta/1SER.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1SER.pssm
psiblast -query ./fasta/1SI3.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1SI3.pssm
psiblast -query ./fasta/1T0K.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1T0K.pssm
psiblast -query ./fasta/1U0B.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1U0B.pssm
psiblast -query ./fasta/1U1Y.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1U1Y.pssm
psiblast -query ./fasta/1UN6.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1UN6.pssm
psiblast -query ./fasta/1UVL.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1UVL.pssm
psiblast -query ./fasta/1VFG.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1VFG.pssm
psiblast -query ./fasta/1VQO.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1VQO.pssm
psiblast -query ./fasta/1WPU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1WPU.pssm
psiblast -query ./fasta/1WSU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1WSU.pssm
psiblast -query ./fasta/1XMQ.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1XMQ.pssm
psiblast -query ./fasta/1XOK.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1XOK.pssm
psiblast -query ./fasta/1YTU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1YTU.pssm
psiblast -query ./fasta/1YVP.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1YVP.pssm
psiblast -query ./fasta/1ZBH.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1ZBH.pssm
psiblast -query ./fasta/1ZBI.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1ZBI.pssm
psiblast -query ./fasta/1ZBL.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1ZBL.pssm
psiblast -query ./fasta/1ZE2.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1ZE2.pssm
psiblast -query ./fasta/1ZH5.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/1ZH5.pssm
psiblast -query ./fasta/2A8V.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2A8V.pssm
psiblast -query ./fasta/2AKE.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2AKE.pssm
psiblast -query ./fasta/2ANN.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2ANN.pssm
psiblast -query ./fasta/2ATW.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2ATW.pssm
psiblast -query ./fasta/2AZ2.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2AZ2.pssm
psiblast -query ./fasta/2B3J.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2B3J.pssm
psiblast -query ./fasta/2BH2.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2BH2.pssm
psiblast -query ./fasta/2BTE.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2BTE.pssm
psiblast -query ./fasta/2BX2.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2BX2.pssm
psiblast -query ./fasta/2CSX.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2CSX.pssm
psiblast -query ./fasta/2D6F.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2D6F.pssm
psiblast -query ./fasta/2DB3.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2DB3.pssm
psiblast -query ./fasta/2DER.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2DER.pssm
psiblast -query ./fasta/2DR8.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2DR8.pssm
psiblast -query ./fasta/2DU3.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2DU3.pssm
psiblast -query ./fasta/2DU4.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2DU4.pssm
psiblast -query ./fasta/2E9T.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2E9T.pssm
psiblast -query ./fasta/2F8K.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2F8K.pssm
psiblast -query ./fasta/2F8S.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2F8S.pssm
psiblast -query ./fasta/2FK6.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2FK6.pssm
psiblast -query ./fasta/2FMT.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2FMT.pssm
psiblast -query ./fasta/2G4B.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2G4B.pssm
psiblast -query ./fasta/2GIC.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2GIC.pssm
psiblast -query ./fasta/2GJW.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2GJW.pssm
psiblast -query ./fasta/2GTT.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2GTT.pssm
psiblast -query ./fasta/2GXB.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2GXB.pssm
psiblast -query ./fasta/2HVY.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2HVY.pssm
psiblast -query ./fasta/2IX1.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2IX1.pssm
psiblast -query ./fasta/2IY5.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2IY5.pssm
psiblast -query ./fasta/2J0Q.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2J0Q.pssm
psiblast -query ./fasta/2JEA.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2JEA.pssm
psiblast -query ./fasta/2JLV.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2JLV.pssm
psiblast -query ./fasta/2NVQ.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2NVQ.pssm
psiblast -query ./fasta/2OZB.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2OZB.pssm
psiblast -query ./fasta/2PJP.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2PJP.pssm
psiblast -query ./fasta/2PLY.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2PLY.pssm
psiblast -query ./fasta/2Q66.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2Q66.pssm
psiblast -query ./fasta/2QK9.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2QK9.pssm
psiblast -query ./fasta/2QUX.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2QUX.pssm
psiblast -query ./fasta/2R8S.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2R8S.pssm
psiblast -query ./fasta/2RFK.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2RFK.pssm
psiblast -query ./fasta/2VPL.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2VPL.pssm
psiblast -query ./fasta/2WJ8.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2WJ8.pssm
psiblast -query ./fasta/2XGJ.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2XGJ.pssm
psiblast -query ./fasta/2XZL.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2XZL.pssm
psiblast -query ./fasta/2XZO.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2XZO.pssm
psiblast -query ./fasta/2ZI0.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2ZI0.pssm
psiblast -query ./fasta/2ZKO.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2ZKO.pssm
psiblast -query ./fasta/2ZM5.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2ZM5.pssm
psiblast -query ./fasta/2ZUE.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2ZUE.pssm
psiblast -query ./fasta/2ZZM.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/2ZZM.pssm
psiblast -query ./fasta/3ADI.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3ADI.pssm
psiblast -query ./fasta/3ADL.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3ADL.pssm
psiblast -query ./fasta/3AEV.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3AEV.pssm
psiblast -query ./fasta/3AHU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3AHU.pssm
psiblast -query ./fasta/3BSO.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3BSO.pssm
psiblast -query ./fasta/3BSU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3BSU.pssm
psiblast -query ./fasta/3BT7.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3BT7.pssm
psiblast -query ./fasta/3CIY.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3CIY.pssm
psiblast -query ./fasta/3CZ3.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3CZ3.pssm
psiblast -query ./fasta/3D2S.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3D2S.pssm
psiblast -query ./fasta/3DH3.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3DH3.pssm
psiblast -query ./fasta/3EPH.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3EPH.pssm
psiblast -query ./fasta/3EQT.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3EQT.pssm
psiblast -query ./fasta/3F73.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3F73.pssm
psiblast -query ./fasta/3FTF.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3FTF.pssm
psiblast -query ./fasta/3G9Y.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3G9Y.pssm
psiblast -query ./fasta/3HL2.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3HL2.pssm
psiblast -query ./fasta/3HTX.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3HTX.pssm
psiblast -query ./fasta/3I5X.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3I5X.pssm
psiblast -query ./fasta/3IAB.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3IAB.pssm
psiblast -query ./fasta/3ICQ.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3ICQ.pssm
psiblast -query ./fasta/3IEV.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3IEV.pssm
psiblast -query ./fasta/3KS8.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3KS8.pssm
psiblast -query ./fasta/3KTW.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3KTW.pssm
psiblast -query ./fasta/3M7N.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3M7N.pssm
psiblast -query ./fasta/3MDG.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3MDG.pssm
psiblast -query ./fasta/3MOJ.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3MOJ.pssm
psiblast -query ./fasta/3NMU.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3NMU.pssm
psiblast -query ./fasta/3NNH.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3NNH.pssm
psiblast -query ./fasta/3O8C.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3O8C.pssm
psiblast -query ./fasta/3RW6.fasta -db ./uniref/uniprot_sprot.fasta -num_iterations 3 -out_ascii_pssm ./pssm/3RW6.pssm
